import { useState } from 'react';
import { ChevronDown, ChevronRight, HelpCircle, CheckCircle, AlertCircle } from 'lucide-react';
import type { BidFaq } from '../lib/types';

interface BidFaqSectionProps {
  faqs: BidFaq[];
  contractorName: string;
}

export function BidFaqSection({ faqs, contractorName }: BidFaqSectionProps) {
  const [expandedFaqs, setExpandedFaqs] = useState<Set<string>>(new Set());

  const toggleExpand = (faqId: string) => {
    const newExpanded = new Set(expandedFaqs);
    if (newExpanded.has(faqId)) {
      newExpanded.delete(faqId);
    } else {
      newExpanded.add(faqId);
    }
    setExpandedFaqs(newExpanded);
  };

  const getConfidenceBadge = (confidence?: string | null) => {
    if (!confidence) return null;

    const badgeConfig = {
      high: { color: 'bg-switch-green-100 text-switch-green-700', label: 'High Confidence' },
      medium: { color: 'bg-amber-100 text-amber-700', label: 'Medium Confidence' },
      low: { color: 'bg-gray-100 text-gray-600', label: 'Low Confidence' },
    };

    const config = badgeConfig[confidence as keyof typeof badgeConfig];
    if (!config) return null;

    return (
      <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium ${config.color}`}>
        {confidence === 'high' && <CheckCircle className="w-3 h-3" />}
        {confidence === 'medium' && <AlertCircle className="w-3 h-3" />}
        {config.label}
      </span>
    );
  };

  const groupedFaqs = {
    pricing: faqs.filter(faq => ['FAQ_01', 'FAQ_02', 'FAQ_03', 'FAQ_04'].includes(faq.faq_key)),
    risk: faqs.filter(faq => ['FAQ_05', 'FAQ_06', 'FAQ_07'].includes(faq.faq_key)),
    technical: faqs.filter(faq => ['FAQ_08', 'FAQ_09', 'FAQ_10'].includes(faq.faq_key)),
    decision: faqs.filter(faq => ['FAQ_11', 'FAQ_12', 'FAQ_13', 'FAQ_14', 'FAQ_15'].includes(faq.faq_key)),
  };

  const groupTitles = {
    pricing: 'Pricing & Value',
    risk: 'Risk Assessment',
    technical: 'Technical Appropriateness',
    decision: 'Decision Guidance',
  };

  if (faqs.length === 0) {
    return (
      <div className="bg-white rounded-xl border-2 border-gray-200 p-12 text-center">
        <HelpCircle className="w-12 h-12 text-gray-300 mx-auto mb-4" />
        <h3 className="text-lg font-semibold text-gray-900 mb-2">No FAQ Data Available Yet</h3>
        <p className="text-gray-600">
          FAQ answers will be generated by AI during bid processing.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {Object.entries(groupedFaqs).map(([groupKey, groupFaqs]) => {
        if (groupFaqs.length === 0) return null;

        return (
          <div key={groupKey} className="bg-white rounded-xl border-2 border-gray-200 shadow-md overflow-hidden">
            <div className="bg-gradient-to-r from-gray-700 to-gray-800 px-5 py-3">
              <h3 className="font-semibold text-white">
                {groupTitles[groupKey as keyof typeof groupTitles]}
              </h3>
            </div>

            <div className="divide-y divide-gray-200">
              {groupFaqs.map((faq) => {
                const isExpanded = expandedFaqs.has(faq.id);
                const hasAnswer = faq.is_answered && faq.answer_text;

                return (
                  <div key={faq.id} className={hasAnswer ? '' : 'bg-gray-50'}>
                    <button
                      onClick={() => toggleExpand(faq.id)}
                      className="w-full px-5 py-4 flex items-start gap-3 hover:bg-gray-50 transition-colors text-left"
                    >
                      <div className="pt-0.5">
                        {isExpanded ? (
                          <ChevronDown className="w-5 h-5 text-gray-500" />
                        ) : (
                          <ChevronRight className="w-5 h-5 text-gray-500" />
                        )}
                      </div>

                      <div className="flex-1 min-w-0">
                        <div className="flex items-start justify-between gap-3">
                          <p className="font-medium text-gray-900 pr-4">{faq.question_text}</p>
                          {hasAnswer && getConfidenceBadge(faq.answer_confidence)}
                        </div>

                        {!hasAnswer && !isExpanded && (
                          <p className="text-sm text-gray-500 mt-1">
                            Answer pending from AI analysis
                          </p>
                        )}
                      </div>
                    </button>

                    {isExpanded && (
                      <div className="px-5 pb-5 pl-14">
                        {hasAnswer ? (
                          <div className="prose prose-sm max-w-none">
                            <p className="text-gray-700 whitespace-pre-wrap">{faq.answer_text}</p>
                          </div>
                        ) : (
                          <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
                            <p className="text-sm text-amber-800">
                              This answer will be generated during bid analysis. The AI will review {contractorName}'s
                              bid and provide detailed insights to help you make an informed decision.
                            </p>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        );
      })}
    </div>
  );
}
