import { useState } from 'react';
import { ChevronDown, ChevronRight, HelpCircle, CheckCircle, AlertCircle, Info, FileText } from 'lucide-react';
import type { FAQData, OverallFAQ, FAQEvidence } from '../lib/types';

interface ProjectFAQSectionProps {
  faqData: FAQData | null;
  className?: string;
}

export function ProjectFAQSection({ faqData, className = '' }: ProjectFAQSectionProps) {
  const [expandedFaqs, setExpandedFaqs] = useState<Set<number>>(new Set([0]));

  const toggleExpand = (index: number) => {
    const newExpanded = new Set(expandedFaqs);
    if (newExpanded.has(index)) {
      newExpanded.delete(index);
    } else {
      newExpanded.add(index);
    }
    setExpandedFaqs(newExpanded);
  };

  const getConfidenceBadge = (confidence: 'high' | 'medium' | 'low') => {
    const badgeConfig = {
      high: { color: 'bg-switch-green-100 text-switch-green-700', label: 'High Confidence', icon: CheckCircle },
      medium: { color: 'bg-amber-100 text-amber-700', label: 'Medium Confidence', icon: AlertCircle },
      low: { color: 'bg-gray-100 text-gray-600', label: 'Low Confidence', icon: Info },
    };

    const config = badgeConfig[confidence];
    const Icon = config.icon;

    return (
      <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium ${config.color}`}>
        <Icon className="w-3 h-3" />
        {config.label}
      </span>
    );
  };

  const renderEvidence = (evidence: FAQEvidence[]) => {
    if (!evidence || evidence.length === 0) return null;

    return (
      <div className="mt-3 pt-3 border-t border-gray-200">
        <p className="text-xs font-medium text-gray-500 mb-2">Evidence:</p>
        <div className="space-y-2">
          {evidence.map((item, idx) => (
            <div key={idx} className="flex items-start gap-2 text-xs">
              <FileText className="w-3 h-3 text-gray-400 mt-0.5 flex-shrink-0" />
              <div>
                <span className="font-medium text-gray-700">
                  {item.source === 'bid' && item.bid_index !== undefined && `Bid ${item.bid_index + 1}`}
                  {item.source === 'researched' && 'Research'}
                  {item.source === 'industry_standard' && 'Industry Standard'}
                </span>
                {item.field && <span className="text-gray-500"> • {item.field}</span>}
                {item.value && <span className="text-gray-600">: {item.value}</span>}
                {item.notes && <p className="text-gray-500 mt-0.5">{item.notes}</p>}
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  };

  if (!faqData || !faqData.overall || faqData.overall.length === 0) {
    return (
      <div className={`bg-white rounded-xl border-2 border-gray-200 p-12 text-center ${className}`}>
        <HelpCircle className="w-12 h-12 text-gray-300 mx-auto mb-4" />
        <h3 className="text-lg font-semibold text-gray-900 mb-2">No FAQ Data Available Yet</h3>
        <p className="text-gray-600">
          FAQ answers will be generated by AI during bid analysis.
        </p>
      </div>
    );
  }

  const sortedFaqs = [...faqData.overall].sort((a, b) => a.display_order - b.display_order);

  return (
    <div className={`space-y-4 ${className}`}>
      <div className="bg-white rounded-xl border-2 border-gray-200 shadow-md overflow-hidden">
        <div className="bg-gradient-to-r from-switch-green-600 to-switch-green-700 px-5 py-4">
          <div className="flex items-center gap-2">
            <HelpCircle className="w-5 h-5 text-white" />
            <h3 className="font-semibold text-white text-lg">
              Frequently Asked Questions
            </h3>
          </div>
          <p className="text-switch-green-50 text-sm mt-1">
            AI-generated answers based on your bids
          </p>
        </div>

        <div className="divide-y divide-gray-200">
          {sortedFaqs.map((faq, index) => {
            const isExpanded = expandedFaqs.has(index);

            return (
              <div key={faq.faq_key || index}>
                <button
                  onClick={() => toggleExpand(index)}
                  className="w-full px-5 py-4 flex items-start gap-3 hover:bg-gray-50 transition-colors text-left"
                >
                  <div className="pt-0.5">
                    {isExpanded ? (
                      <ChevronDown className="w-5 h-5 text-gray-500" />
                    ) : (
                      <ChevronRight className="w-5 h-5 text-gray-500" />
                    )}
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-start justify-between gap-3 flex-wrap">
                      <p className="font-medium text-gray-900 pr-4">{faq.question_text}</p>
                      {getConfidenceBadge(faq.answer_confidence)}
                    </div>
                  </div>
                </button>

                {isExpanded && (
                  <div className="px-5 pb-5 pl-14">
                    <div className="prose prose-sm max-w-none">
                      <p className="text-gray-700 whitespace-pre-wrap leading-relaxed">
                        {faq.answer_text}
                      </p>
                    </div>
                    {renderEvidence(faq.evidence)}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {faqData.by_bid && faqData.by_bid.length > 0 && (
        <div className="bg-blue-50 border-2 border-blue-200 rounded-xl p-4">
          <div className="flex items-start gap-2">
            <Info className="w-5 h-5 text-blue-600 mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-sm font-medium text-blue-900">Bid-Specific FAQs Available</p>
              <p className="text-sm text-blue-700 mt-1">
                View individual bid cards for contractor-specific questions and answers.
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
