import type { ContractorBid, BidEquipment, BidQuestion } from '../types';

export interface SampleBidData {
  bid: Partial<ContractorBid>;
  equipment: Partial<BidEquipment>[];
  questions: Partial<BidQuestion>[];
}

export const SAMPLE_BIDS: SampleBidData[] = [
  {
    bid: {
      contractor_name: 'Bay Area Heat Pump Pros',
      contractor_company: 'Bay Area Heat Pump Pros LLC',
      contractor_phone: '(415) 555-1234',
      contractor_email: 'info@baheatpumppros.com',
      contractor_license: 'CSLB #1234567',
      contractor_license_state: 'CA',
      contractor_website: 'https://baheatpumppros.com',
      contractor_years_in_business: 15,
      contractor_google_rating: 4.8,
      contractor_google_review_count: 247,
      contractor_certifications: ['NATE Certified', 'EPA 608', 'Carrier Factory Authorized'],
      contractor_is_switch_preferred: true,
      total_bid_amount: 18500,
      labor_cost: 4500,
      equipment_cost: 9800,
      materials_cost: 1200,
      permit_cost: 850,
      total_before_rebates: 18500,
      estimated_rebates: 3500,
      total_after_rebates: 15000,
      estimated_days: 2,
      labor_warranty_years: 2,
      equipment_warranty_years: 10,
      deposit_required: 3700,
      deposit_percentage: 20,
      financing_offered: true,
      financing_terms: '0% APR for 24 months through GreenSky',
      scope_summary: 'Complete heat pump system installation with panel upgrade',
      inclusions: [
        'Remove existing gas furnace and AC',
        'Install Carrier Infinity 26 heat pump',
        'Install new air handler',
        'Install Infinity Touch thermostat',
        '200A electrical panel upgrade',
        'Permits and inspections',
        'System commissioning',
        'Homeowner training',
      ],
      exclusions: [
        'Ductwork modifications',
        'Drywall repair',
        'Landscaping restoration',
      ],
      extraction_confidence: 'high',
      verified_by_user: false,
      is_favorite: false,
    },
    equipment: [
      {
        equipment_type: 'outdoor_unit',
        brand: 'Carrier',
        model_number: '25VNA836A003',
        model_name: 'Infinity 26 Heat Pump',
        capacity_btu: 36000,
        capacity_tons: 3.0,
        seer_rating: 26,
        seer2_rating: 24.5,
        hspf_rating: 13,
        hspf2_rating: 10.5,
        variable_speed: true,
        stages: 99,
        refrigerant_type: 'R-410A',
        sound_level_db: 51,
        voltage: 240,
        energy_star_certified: true,
        energy_star_most_efficient: true,
        equipment_cost: 7200,
        confidence: 'high',
      },
      {
        equipment_type: 'indoor_unit',
        brand: 'Carrier',
        model_number: 'FV4CNB003',
        model_name: 'Infinity Series Air Handler',
        variable_speed: true,
        equipment_cost: 2600,
        confidence: 'high',
      },
    ],
    questions: [
      {
        question_text: 'What is the exact start date availability?',
        question_category: 'timeline',
        priority: 'high',
        is_answered: false,
        auto_generated: true,
      },
      {
        question_text: 'Is the 10-year warranty transferable to a new homeowner?',
        question_category: 'warranty',
        priority: 'medium',
        is_answered: false,
        auto_generated: true,
      },
    ],
  },
  {
    bid: {
      contractor_name: 'GreenTech HVAC Solutions',
      contractor_company: 'GreenTech HVAC Solutions Inc',
      contractor_phone: '(510) 555-9876',
      contractor_email: 'sales@greentechhvac.com',
      contractor_license: 'CSLB #9876543',
      contractor_license_state: 'CA',
      contractor_website: 'https://greentechhvac.com',
      contractor_years_in_business: 8,
      contractor_google_rating: 4.6,
      contractor_google_review_count: 156,
      contractor_certifications: ['NATE Certified', 'EPA 608', 'Mitsubishi Diamond Contractor'],
      contractor_is_switch_preferred: false,
      total_bid_amount: 16800,
      labor_cost: 3800,
      equipment_cost: 9200,
      materials_cost: 1000,
      permit_cost: 750,
      total_before_rebates: 16800,
      estimated_rebates: 3200,
      total_after_rebates: 13600,
      estimated_days: 3,
      labor_warranty_years: 1,
      equipment_warranty_years: 12,
      deposit_required: 5040,
      deposit_percentage: 30,
      financing_offered: true,
      financing_terms: '5.99% APR for 60 months',
      scope_summary: 'Heat pump installation with existing electrical panel',
      inclusions: [
        'Remove existing HVAC system',
        'Install Mitsubishi heat pump',
        'Install air handler',
        'Ecobee smart thermostat',
        'Permits and inspections',
        'System startup',
      ],
      exclusions: [
        'Electrical panel upgrade (additional $2,500)',
        'Ductwork modifications',
        'Drywall repair',
      ],
      extraction_confidence: 'high',
      verified_by_user: false,
      is_favorite: false,
    },
    equipment: [
      {
        equipment_type: 'outdoor_unit',
        brand: 'Mitsubishi',
        model_number: 'SUZ-KA36NAHZ',
        model_name: 'Hyper-Heating INVERTER',
        capacity_btu: 36000,
        capacity_tons: 3.0,
        seer_rating: 20,
        seer2_rating: 18.5,
        hspf_rating: 12.5,
        hspf2_rating: 10.2,
        variable_speed: true,
        stages: 99,
        refrigerant_type: 'R-410A',
        sound_level_db: 48,
        voltage: 230,
        energy_star_certified: true,
        energy_star_most_efficient: false,
        equipment_cost: 6800,
        confidence: 'high',
      },
      {
        equipment_type: 'indoor_unit',
        brand: 'Mitsubishi',
        model_number: 'SVZ-KP36NA',
        model_name: 'Multi-Position Air Handler',
        variable_speed: true,
        equipment_cost: 2400,
        confidence: 'high',
      },
    ],
    questions: [
      {
        question_text: 'Will the existing electrical panel support the heat pump?',
        question_category: 'scope',
        priority: 'high',
        is_answered: false,
        auto_generated: true,
      },
      {
        question_text: 'Why is the labor warranty only 1 year?',
        question_category: 'warranty',
        priority: 'high',
        is_answered: false,
        auto_generated: true,
      },
    ],
  },
  {
    bid: {
      contractor_name: 'Comfort First Heating & Cooling',
      contractor_company: 'Comfort First H&C',
      contractor_phone: '(408) 555-4321',
      contractor_email: 'quotes@comfortfirst.com',
      contractor_license: 'CSLB #5678901',
      contractor_license_state: 'CA',
      contractor_years_in_business: 22,
      contractor_google_rating: 4.9,
      contractor_google_review_count: 412,
      contractor_certifications: ['NATE Certified', 'EPA 608', 'Lennox Premier Dealer', 'BPI Certified'],
      contractor_is_switch_preferred: true,
      total_bid_amount: 21500,
      labor_cost: 5500,
      equipment_cost: 11500,
      materials_cost: 1500,
      permit_cost: 950,
      total_before_rebates: 21500,
      estimated_rebates: 4000,
      total_after_rebates: 17500,
      estimated_days: 2,
      labor_warranty_years: 5,
      equipment_warranty_years: 10,
      deposit_required: 4300,
      deposit_percentage: 20,
      financing_offered: true,
      financing_terms: '0% APR for 36 months or 2.99% for 72 months',
      scope_summary: 'Premium installation with load calculation and duct sealing',
      inclusions: [
        'Manual J load calculation',
        'Remove existing system',
        'Install Lennox XP25 heat pump',
        'Install air handler with ECM motor',
        'iComfort S30 smart thermostat',
        'Electrical circuit upgrade',
        'Duct sealing and testing',
        'Permits and inspections',
        'Professional commissioning',
        'First year maintenance included',
      ],
      exclusions: [
        'Full ductwork replacement',
        'Drywall repair',
      ],
      extraction_confidence: 'high',
      verified_by_user: false,
      is_favorite: false,
    },
    equipment: [
      {
        equipment_type: 'outdoor_unit',
        brand: 'Lennox',
        model_number: 'XP25-036-230',
        model_name: 'XP25 Variable Capacity Heat Pump',
        capacity_btu: 36000,
        capacity_tons: 3.0,
        seer_rating: 25.5,
        seer2_rating: 23.5,
        hspf_rating: 11.5,
        hspf2_rating: 9.8,
        variable_speed: true,
        stages: 99,
        refrigerant_type: 'R-410A',
        sound_level_db: 59,
        voltage: 230,
        energy_star_certified: true,
        energy_star_most_efficient: true,
        equipment_cost: 8500,
        confidence: 'high',
      },
      {
        equipment_type: 'indoor_unit',
        brand: 'Lennox',
        model_number: 'CBX40UHV-036',
        model_name: 'Variable Speed Air Handler',
        variable_speed: true,
        equipment_cost: 3000,
        confidence: 'high',
      },
    ],
    questions: [
      {
        question_text: 'What does the Manual J load calculation include?',
        question_category: 'scope',
        priority: 'medium',
        is_answered: false,
        auto_generated: true,
      },
    ],
  },
];

export const SAMPLE_REBATE_PROGRAMS = [
  {
    program_name: 'Federal 25C Tax Credit',
    program_code: 'FED-25C',
    description: 'Tax credit for energy efficient home improvements',
    program_type: 'federal',
    available_nationwide: true,
    rebate_percentage: 30,
    max_rebate: 2000,
    income_qualified: false,
    stackable: true,
    is_active: true,
  },
  {
    program_name: 'BayREN Home+ Rebate',
    program_code: 'BAYREN-HP',
    description: 'Bay Area regional heat pump rebate program',
    program_type: 'utility',
    available_states: ['CA'],
    rebate_amount: 1500,
    income_qualified: false,
    stackable: true,
    is_active: true,
  },
];
