-- ============================================================================
-- Migration: Add MindPal v10 Tables and Columns
-- Created: 2026-02-18
-- Description: Creates bid_faqs, project_faqs, incentive_programs tables
--              and adds missing columns to contractor_bids for MindPal v10 workflow
-- ============================================================================

-- ============================================
-- TABLE 1: bid_faqs (per-bid FAQs)
-- ============================================
DROP TABLE IF EXISTS bid_faqs CASCADE;

CREATE TABLE bid_faqs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  bid_id UUID REFERENCES contractor_bids(id) ON DELETE CASCADE NOT NULL,
  
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  faq_category TEXT,
  answer_confidence TEXT,
  
  display_order INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_bid_faqs_bid ON bid_faqs(bid_id);
CREATE INDEX idx_bid_faqs_faq_category ON bid_faqs(faq_category);

COMMENT ON TABLE bid_faqs IS 'Per-bid FAQs generated by MindPal';
COMMENT ON COLUMN bid_faqs.faq_category IS 'Category: pricing, warranty, equipment, scope, contractor, timeline';
COMMENT ON COLUMN bid_faqs.answer_confidence IS 'Confidence level: high, medium, low';

-- ============================================
-- TABLE 2: project_faqs (overall project FAQs)
-- Note: MindPal calls this "overall_faqs" but front-end uses "project_faqs"
-- ============================================
DROP TABLE IF EXISTS project_faqs CASCADE;

CREATE TABLE project_faqs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE NOT NULL,
  
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  faq_category TEXT,
  sources TEXT[],
  
  display_order INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_project_faqs_project ON project_faqs(project_id);
CREATE INDEX idx_project_faqs_faq_category ON project_faqs(faq_category);

COMMENT ON TABLE project_faqs IS 'Overall project-level FAQs comparing all bids';
COMMENT ON COLUMN project_faqs.faq_category IS 'Category: comparison, recommendation, general, incentives';

-- ============================================
-- TABLE 3: incentive_programs (per-bid incentives found)
-- ============================================
DROP TABLE IF EXISTS incentive_programs CASCADE;

CREATE TABLE incentive_programs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  bid_id UUID REFERENCES contractor_bids(id) ON DELETE CASCADE NOT NULL,
  
  program_name TEXT NOT NULL,
  program_type TEXT NOT NULL,
  
  incentive_amount_numeric_min DECIMAL(12,2),
  incentive_amount_numeric_max DECIMAL(12,2),
  incentive_amount_string TEXT,
  
  equipment_requirements TEXT,
  eligibility_requirements TEXT,
  income_limits TEXT,
  application_process TEXT,
  
  can_stack_with_other_incentives BOOLEAN,
  stacking_notes TEXT,
  verification_source TEXT,
  still_active BOOLEAN DEFAULT true,
  
  research_confidence TEXT,
  research_notes TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_incentive_programs_bid ON incentive_programs(bid_id);
CREATE INDEX idx_incentive_programs_type ON incentive_programs(program_type);

COMMENT ON TABLE incentive_programs IS 'Incentive programs found per bid by MindPal Incentive Finder';
COMMENT ON COLUMN incentive_programs.program_type IS 'Type: federal, state, utility, local, manufacturer';
COMMENT ON COLUMN incentive_programs.research_confidence IS 'Confidence level: high, medium, low';

-- ============================================
-- ADD MISSING COLUMNS TO contractor_bids
-- ============================================

-- Bid index (for ordering)
ALTER TABLE contractor_bids
  ADD COLUMN IF NOT EXISTS bid_index INTEGER;

-- Incentive summary fields
ALTER TABLE contractor_bids
  ADD COLUMN IF NOT EXISTS incentive_electric_utility TEXT,
  ADD COLUMN IF NOT EXISTS incentive_gas_utility TEXT,
  ADD COLUMN IF NOT EXISTS incentive_cca TEXT,
  ADD COLUMN IF NOT EXISTS incentive_ren TEXT,
  ADD COLUMN IF NOT EXISTS incentive_total_potential_low DECIMAL(12,2),
  ADD COLUMN IF NOT EXISTS incentive_total_potential_high DECIMAL(12,2),
  ADD COLUMN IF NOT EXISTS incentive_programs_found_count INTEGER,
  ADD COLUMN IF NOT EXISTS incentive_research_confidence TEXT,
  ADD COLUMN IF NOT EXISTS incentive_research_notes TEXT;

-- Scoring metadata
ALTER TABLE contractor_bids
  ADD COLUMN IF NOT EXISTS score_confidence DECIMAL(5,2),
  ADD COLUMN IF NOT EXISTS scoring_notes TEXT,
  ADD COLUMN IF NOT EXISTS ranking_recommendation TEXT;

-- Comments
COMMENT ON COLUMN contractor_bids.bid_index IS 'Order of bid in analysis (0-indexed)';
COMMENT ON COLUMN contractor_bids.incentive_electric_utility IS 'Electric utility serving customer address';
COMMENT ON COLUMN contractor_bids.incentive_total_potential_low IS 'Minimum total incentives available';
COMMENT ON COLUMN contractor_bids.incentive_total_potential_high IS 'Maximum total incentives available';
COMMENT ON COLUMN contractor_bids.score_confidence IS 'Confidence in scoring (0-100)';
COMMENT ON COLUMN contractor_bids.ranking_recommendation IS 'AI recommendation: excellent, good, fair, poor';

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

ALTER TABLE bid_faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE incentive_programs ENABLE ROW LEVEL SECURITY;

-- bid_faqs policy (through bid → project)
CREATE POLICY bid_faqs_policy ON bid_faqs
  FOR ALL USING (
    bid_id IN (
      SELECT id FROM contractor_bids 
      WHERE project_id IN (
        SELECT id FROM projects 
        WHERE user_id IN (
          SELECT id FROM users_ext 
          WHERE auth_user_id = auth.uid() 
          OR auth_user_id IS NULL
        )
      )
    )
  );

-- project_faqs policy
CREATE POLICY project_faqs_policy ON project_faqs
  FOR ALL USING (
    project_id IN (
      SELECT id FROM projects 
      WHERE user_id IN (
        SELECT id FROM users_ext 
        WHERE auth_user_id = auth.uid() 
        OR auth_user_id IS NULL
      )
    )
  );

-- incentive_programs policy
CREATE POLICY incentive_programs_policy ON incentive_programs
  FOR ALL USING (
    bid_id IN (
      SELECT id FROM contractor_bids 
      WHERE project_id IN (
        SELECT id FROM projects 
        WHERE user_id IN (
          SELECT id FROM users_ext 
          WHERE auth_user_id = auth.uid() 
          OR auth_user_id IS NULL
        )
      )
    )
  );
